; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-audio-kit]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600


build_flags =
    -DCORE_DEBUG_LEVEL=1
    -DARDUINO_RUNNING_CORE=1
    -DARDUINO_EVENT_RUNNING_CORE=1

; Se usi porta seriale fissa, puoi impostarla (opzionale):
; upload_port = COM3
; monitor_port = COM3

; Libreria I2S è inclusa nell’ESP32, ma se useremo altre librerie le aggiungeremo qui

lib_deps =
    ; exocet22/btAudio@^1.1.0
    ; m5stack/Module-Audio@^0.0.1
    ; msteltman/ESP32Sampler@^1.1.0

